name: CI Pipeline

on:
  push:
    branches:
      - main # or master, depending on your main branch name

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run a simple test
      run: |
        python -c "print('Testing...')\nfrom flask import Flask; app = Flask(__name__); assert isinstance(app, Flask)"

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-flask-app:latest .

    - name: Tag Docker image
      run: |
        docker tag my-flask-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest